import { markdownTable, pathExists, readContentEntries, writeText } from '../shared/toolkit.ts'

const entries = await readContentEntries()
const rows = [
  ['Area', 'Status'],
  ['Content items', String(entries.length)],
  ['Search index', pathExists('public/search/search-index.json') ? 'available' : 'missing'],
  ['Sitemap asset', pathExists('public/sitemap.xml') ? 'available' : 'generated by Next.js route'],
  ['llms.txt', pathExists('public/llms.txt') ? 'available' : 'missing'],
]

writeText('reports/summary.md', `# Script Pipeline Summary\n\n${markdownTable(rows)}\n`)
console.log('Generated reports/summary.md.')
